baseURL: 'https://pcrutchl.github.io'
languageCode: en-us
title: 'supercres.net'
theme: ananke

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

params:
  text_color: ''
  author: ''
  favicon: ''
  site_logo: ''
  description: 'Data Science, Psychology, Coffee'
  background_color_class: bg-black
  recent_posts_number: 3
  ananke_socials:
    - name: instagram
      url: 'https://instagram.com/supercres'
    - name: github
      url: 'https://github.com/pcrutchl'

